/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConnectorDefinitionsGetByNameResponseConnectorSpec
 */
public class ConnectorDefinitionsGetByNameResponseConnectorSpecTest {
    private final ConnectorDefinitionsGetByNameResponseConnectorSpec model = new ConnectorDefinitionsGetByNameResponseConnectorSpec();

    /**
     * Model tests for ConnectorDefinitionsGetByNameResponseConnectorSpec
     */
    @Test
    public void testConnectorDefinitionsGetByNameResponseConnectorSpec() {
        // TODO: test ConnectorDefinitionsGetByNameResponseConnectorSpec
    }

    /**
     * Test the property 'documentationUrl'
     */
    @Test
    public void documentationUrlTest() {
        // TODO: test documentationUrl
    }

    /**
     * Test the property 'connectionSpecification'
     */
    @Test
    public void connectionSpecificationTest() {
        // TODO: test connectionSpecification
    }

    /**
     * Test the property 'supportsNormalization'
     */
    @Test
    public void supportsNormalizationTest() {
        // TODO: test supportsNormalization
    }

    /**
     * Test the property 'supportsDbt'
     */
    @Test
    public void supportsDbtTest() {
        // TODO: test supportsDbt
    }

    /**
     * Test the property 'streamType'
     */
    @Test
    public void streamTypeTest() {
        // TODO: test streamType
    }

}
