/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConnectorDefinitionsCheckConnectionRequest
 */
public class ConnectorDefinitionsCheckConnectionRequestTest {
    private final ConnectorDefinitionsCheckConnectionRequest model = new ConnectorDefinitionsCheckConnectionRequest();

    /**
     * Model tests for ConnectorDefinitionsCheckConnectionRequest
     */
    @Test
    public void testConnectorDefinitionsCheckConnectionRequest() {
        // TODO: test ConnectorDefinitionsCheckConnectionRequest
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'connectionSpec'
     */
    @Test
    public void connectionSpecTest() {
        // TODO: test connectionSpec
    }

}
