/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ConnectorsCreateNewConnectorResponseData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConnectorsCreateNewConnectorResponse
 */
public class ConnectorsCreateNewConnectorResponseTest {
    private final ConnectorsCreateNewConnectorResponse model = new ConnectorsCreateNewConnectorResponse();

    /**
     * Model tests for ConnectorsCreateNewConnectorResponse
     */
    @Test
    public void testConnectorsCreateNewConnectorResponse() {
        // TODO: test ConnectorsCreateNewConnectorResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
