/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsListAllModelsResponseDataInnerAttributes
 */
public class ModelsListAllModelsResponseDataInnerAttributesTest {
    private final ModelsListAllModelsResponseDataInnerAttributes model = new ModelsListAllModelsResponseDataInnerAttributes();

    /**
     * Model tests for ModelsListAllModelsResponseDataInnerAttributes
     */
    @Test
    public void testModelsListAllModelsResponseDataInnerAttributes() {
        // TODO: test ModelsListAllModelsResponseDataInnerAttributes
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'queryType'
     */
    @Test
    public void queryTypeTest() {
        // TODO: test queryType
    }

    /**
     * Test the property 'primaryKey'
     */
    @Test
    public void primaryKeyTest() {
        // TODO: test primaryKey
    }

    /**
     * Test the property 'connectorId'
     */
    @Test
    public void connectorIdTest() {
        // TODO: test connectorId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
