/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner
 */
public class ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInnerTest {
    private final ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner model = new ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner();

    /**
     * Model tests for ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner
     */
    @Test
    public void testReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner() {
        // TODO: test ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner
    }

    /**
     * Test the property 'timeSlice'
     */
    @Test
    public void timeSliceTest() {
        // TODO: test timeSlice
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'failedCount'
     */
    @Test
    public void failedCountTest() {
        // TODO: test failedCount
    }

    /**
     * Test the property 'successCount'
     */
    @Test
    public void successCountTest() {
        // TODO: test successCount
    }

}
