/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
 */
public class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterTest {
    private final SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter model = new SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter();

    /**
     * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
     */
    @Test
    public void testSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter() {
        // TODO: test SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
    }

    /**
     * Test the property 'cast'
     */
    @Test
    public void castTest() {
        // TODO: test cast
    }

    /**
     * Test the property 'regexReplace'
     */
    @Test
    public void regexReplaceTest() {
        // TODO: test regexReplace
    }

}
