/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncRunsListBySyncIdResponseDataInner;
import com.konfigthis.client.model.SyncRunsListBySyncIdResponseLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncRunsListBySyncIdResponse
 */
public class SyncRunsListBySyncIdResponseTest {
    private final SyncRunsListBySyncIdResponse model = new SyncRunsListBySyncIdResponse();

    /**
     * Model tests for SyncRunsListBySyncIdResponse
     */
    @Test
    public void testSyncRunsListBySyncIdResponse() {
        // TODO: test SyncRunsListBySyncIdResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
