/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncRunsListBySyncIdResponseDataInnerAttributes
 */
public class SyncRunsListBySyncIdResponseDataInnerAttributesTest {
    private final SyncRunsListBySyncIdResponseDataInnerAttributes model = new SyncRunsListBySyncIdResponseDataInnerAttributes();

    /**
     * Model tests for SyncRunsListBySyncIdResponseDataInnerAttributes
     */
    @Test
    public void testSyncRunsListBySyncIdResponseDataInnerAttributes() {
        // TODO: test SyncRunsListBySyncIdResponseDataInnerAttributes
    }

    /**
     * Test the property 'syncId'
     */
    @Test
    public void syncIdTest() {
        // TODO: test syncId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'totalQueryRows'
     */
    @Test
    public void totalQueryRowsTest() {
        // TODO: test totalQueryRows
    }

    /**
     * Test the property 'totalRows'
     */
    @Test
    public void totalRowsTest() {
        // TODO: test totalRows
    }

    /**
     * Test the property 'successfulRows'
     */
    @Test
    public void successfulRowsTest() {
        // TODO: test successfulRows
    }

    /**
     * Test the property 'failedRows'
     */
    @Test
    public void failedRowsTest() {
        // TODO: test failedRows
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
