/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncRecordsListForSyncRunResponseDataInnerAttributesRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncRecordsListForSyncRunResponseDataInnerAttributes
 */
public class SyncRecordsListForSyncRunResponseDataInnerAttributesTest {
    private final SyncRecordsListForSyncRunResponseDataInnerAttributes model = new SyncRecordsListForSyncRunResponseDataInnerAttributes();

    /**
     * Model tests for SyncRecordsListForSyncRunResponseDataInnerAttributes
     */
    @Test
    public void testSyncRecordsListForSyncRunResponseDataInnerAttributes() {
        // TODO: test SyncRecordsListForSyncRunResponseDataInnerAttributes
    }

    /**
     * Test the property 'syncId'
     */
    @Test
    public void syncIdTest() {
        // TODO: test syncId
    }

    /**
     * Test the property 'syncRunId'
     */
    @Test
    public void syncRunIdTest() {
        // TODO: test syncRunId
    }

    /**
     * Test the property 'record'
     */
    @Test
    public void recordTest() {
        // TODO: test record
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
