/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate
 */
public class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateTest {
    private final SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate model = new SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate();

    /**
     * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate
     */
    @Test
    public void testSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate() {
        // TODO: test SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

}
