/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncsCreateNewSyncOperationRequestSync;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsCreateNewSyncOperationRequest
 */
public class SyncsCreateNewSyncOperationRequestTest {
    private final SyncsCreateNewSyncOperationRequest model = new SyncsCreateNewSyncOperationRequest();

    /**
     * Model tests for SyncsCreateNewSyncOperationRequest
     */
    @Test
    public void testSyncsCreateNewSyncOperationRequest() {
        // TODO: test SyncsCreateNewSyncOperationRequest
    }

    /**
     * Test the property 'sync'
     */
    @Test
    public void syncTest() {
        // TODO: test sync
    }

}
