/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp
 */
public class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestampTest {
    private final SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp model = new SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp();

    /**
     * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp
     */
    @Test
    public void testSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp() {
        // TODO: test SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
