/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic;
import com.konfigthis.client.model.SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes
 */
public class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTest {
    private final SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes model = new SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes();

    /**
     * Model tests for SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes
     */
    @Test
    public void testSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes() {
        // TODO: test SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypes
    }

    /**
     * Test the property 'standard'
     */
    @Test
    public void standardTest() {
        // TODO: test standard
    }

    /**
     * Test the property '_static'
     */
    @Test
    public void _staticTest() {
        // TODO: test _static
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
