/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SyncsListOperationsResponseDataInnerAttributes
 */
public class SyncsListOperationsResponseDataInnerAttributesTest {
    private final SyncsListOperationsResponseDataInnerAttributes model = new SyncsListOperationsResponseDataInnerAttributes();

    /**
     * Model tests for SyncsListOperationsResponseDataInnerAttributes
     */
    @Test
    public void testSyncsListOperationsResponseDataInnerAttributes() {
        // TODO: test SyncsListOperationsResponseDataInnerAttributes
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'destinationId'
     */
    @Test
    public void destinationIdTest() {
        // TODO: test destinationId
    }

    /**
     * Test the property 'modelId'
     */
    @Test
    public void modelIdTest() {
        // TODO: test modelId
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'scheduleType'
     */
    @Test
    public void scheduleTypeTest() {
        // TODO: test scheduleType
    }

    /**
     * Test the property 'syncMode'
     */
    @Test
    public void syncModeTest() {
        // TODO: test syncMode
    }

    /**
     * Test the property 'syncInterval'
     */
    @Test
    public void syncIntervalTest() {
        // TODO: test syncInterval
    }

    /**
     * Test the property 'syncIntervalUnit'
     */
    @Test
    public void syncIntervalUnitTest() {
        // TODO: test syncIntervalUnit
    }

    /**
     * Test the property 'streamName'
     */
    @Test
    public void streamNameTest() {
        // TODO: test streamName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
