/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ConnectorsDiscoverCatalogInfoResponseDataAttributes
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ConnectorsDiscoverCatalogInfoResponseDataAttributes {
  public static final String SERIALIZED_NAME_CONNECTOR_ID = "connector_id";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_ID)
  private Integer connectorId;

  public static final String SERIALIZED_NAME_WORKSPACE_ID = "workspace_id";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ID)
  private Integer workspaceId;

  public static final String SERIALIZED_NAME_CATALOG = "catalog";
  @SerializedName(SERIALIZED_NAME_CATALOG)
  private ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog catalog;

  public static final String SERIALIZED_NAME_CATALOG_HASH = "catalog_hash";
  @SerializedName(SERIALIZED_NAME_CATALOG_HASH)
  private String catalogHash;

  public ConnectorsDiscoverCatalogInfoResponseDataAttributes() {
  }

  public ConnectorsDiscoverCatalogInfoResponseDataAttributes connectorId(Integer connectorId) {
    
    
    
    
    this.connectorId = connectorId;
    return this;
  }

   /**
   * Get connectorId
   * @return connectorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getConnectorId() {
    return connectorId;
  }


  public void setConnectorId(Integer connectorId) {
    
    
    
    this.connectorId = connectorId;
  }


  public ConnectorsDiscoverCatalogInfoResponseDataAttributes workspaceId(Integer workspaceId) {
    
    
    
    
    this.workspaceId = workspaceId;
    return this;
  }

   /**
   * Get workspaceId
   * @return workspaceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWorkspaceId() {
    return workspaceId;
  }


  public void setWorkspaceId(Integer workspaceId) {
    
    
    
    this.workspaceId = workspaceId;
  }


  public ConnectorsDiscoverCatalogInfoResponseDataAttributes catalog(ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog catalog) {
    
    
    
    
    this.catalog = catalog;
    return this;
  }

   /**
   * Get catalog
   * @return catalog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog getCatalog() {
    return catalog;
  }


  public void setCatalog(ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog catalog) {
    
    
    
    this.catalog = catalog;
  }


  public ConnectorsDiscoverCatalogInfoResponseDataAttributes catalogHash(String catalogHash) {
    
    
    
    
    this.catalogHash = catalogHash;
    return this;
  }

   /**
   * Get catalogHash
   * @return catalogHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCatalogHash() {
    return catalogHash;
  }


  public void setCatalogHash(String catalogHash) {
    
    
    
    this.catalogHash = catalogHash;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ConnectorsDiscoverCatalogInfoResponseDataAttributes instance itself
   */
  public ConnectorsDiscoverCatalogInfoResponseDataAttributes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorsDiscoverCatalogInfoResponseDataAttributes connectorsDiscoverCatalogInfoResponseDataAttributes = (ConnectorsDiscoverCatalogInfoResponseDataAttributes) o;
    return Objects.equals(this.connectorId, connectorsDiscoverCatalogInfoResponseDataAttributes.connectorId) &&
        Objects.equals(this.workspaceId, connectorsDiscoverCatalogInfoResponseDataAttributes.workspaceId) &&
        Objects.equals(this.catalog, connectorsDiscoverCatalogInfoResponseDataAttributes.catalog) &&
        Objects.equals(this.catalogHash, connectorsDiscoverCatalogInfoResponseDataAttributes.catalogHash)&&
        Objects.equals(this.additionalProperties, connectorsDiscoverCatalogInfoResponseDataAttributes.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectorId, workspaceId, catalog, catalogHash, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorsDiscoverCatalogInfoResponseDataAttributes {\n");
    sb.append("    connectorId: ").append(toIndentedString(connectorId)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
    sb.append("    catalogHash: ").append(toIndentedString(catalogHash)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("connector_id");
    openapiFields.add("workspace_id");
    openapiFields.add("catalog");
    openapiFields.add("catalog_hash");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConnectorsDiscoverCatalogInfoResponseDataAttributes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ConnectorsDiscoverCatalogInfoResponseDataAttributes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConnectorsDiscoverCatalogInfoResponseDataAttributes is not found in the empty JSON string", ConnectorsDiscoverCatalogInfoResponseDataAttributes.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `catalog`
      if (jsonObj.get("catalog") != null && !jsonObj.get("catalog").isJsonNull()) {
        ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalog.validateJsonObject(jsonObj.getAsJsonObject("catalog"));
      }
      if ((jsonObj.get("catalog_hash") != null && !jsonObj.get("catalog_hash").isJsonNull()) && !jsonObj.get("catalog_hash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `catalog_hash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("catalog_hash").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectorsDiscoverCatalogInfoResponseDataAttributes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectorsDiscoverCatalogInfoResponseDataAttributes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectorsDiscoverCatalogInfoResponseDataAttributes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectorsDiscoverCatalogInfoResponseDataAttributes.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectorsDiscoverCatalogInfoResponseDataAttributes>() {
           @Override
           public void write(JsonWriter out, ConnectorsDiscoverCatalogInfoResponseDataAttributes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectorsDiscoverCatalogInfoResponseDataAttributes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ConnectorsDiscoverCatalogInfoResponseDataAttributes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConnectorsDiscoverCatalogInfoResponseDataAttributes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConnectorsDiscoverCatalogInfoResponseDataAttributes
  * @throws IOException if the JSON string is invalid with respect to ConnectorsDiscoverCatalogInfoResponseDataAttributes
  */
  public static ConnectorsDiscoverCatalogInfoResponseDataAttributes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectorsDiscoverCatalogInfoResponseDataAttributes.class);
  }

 /**
  * Convert an instance of ConnectorsDiscoverCatalogInfoResponseDataAttributes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

