/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ConnectorsCreateNewConnectorRequestConnector
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ConnectorsCreateNewConnectorRequestConnector {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * Gets or Sets connectorType
   */
  @JsonAdapter(ConnectorTypeEnum.Adapter.class)
 public enum ConnectorTypeEnum {
    SOURCE("source"),
    
    DESTINATION("destination");

    private String value;

    ConnectorTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConnectorTypeEnum fromValue(String value) {
      for (ConnectorTypeEnum b : ConnectorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ConnectorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConnectorTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConnectorTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConnectorTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CONNECTOR_TYPE = "connector_type";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_TYPE)
  private ConnectorTypeEnum connectorType;

  public static final String SERIALIZED_NAME_CONNECTOR_NAME = "connector_name";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_NAME)
  private String connectorName;

  public static final String SERIALIZED_NAME_CONFIGURATION = "configuration";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION)
  private Map<String, Object> _configuration = new HashMap<>();

  public ConnectorsCreateNewConnectorRequestConnector() {
  }

  public ConnectorsCreateNewConnectorRequestConnector name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public ConnectorsCreateNewConnectorRequestConnector connectorType(ConnectorTypeEnum connectorType) {
    
    
    
    
    this.connectorType = connectorType;
    return this;
  }

   /**
   * Get connectorType
   * @return connectorType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ConnectorTypeEnum getConnectorType() {
    return connectorType;
  }


  public void setConnectorType(ConnectorTypeEnum connectorType) {
    
    
    
    this.connectorType = connectorType;
  }


  public ConnectorsCreateNewConnectorRequestConnector connectorName(String connectorName) {
    
    
    
    
    this.connectorName = connectorName;
    return this;
  }

   /**
   * Get connectorName
   * @return connectorName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getConnectorName() {
    return connectorName;
  }


  public void setConnectorName(String connectorName) {
    
    
    
    this.connectorName = connectorName;
  }


  public ConnectorsCreateNewConnectorRequestConnector _configuration(Map<String, Object> _configuration) {
    
    
    
    
    this._configuration = _configuration;
    return this;
  }

  public ConnectorsCreateNewConnectorRequestConnector putConfigurationItem(String key, Object _configurationItem) {
    this._configuration.put(key, _configurationItem);
    return this;
  }

   /**
   * Configuration details for the connector. Structure depends on the connector definition.
   * @return _configuration
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Configuration details for the connector. Structure depends on the connector definition.")

  public Map<String, Object> getConfiguration() {
    return _configuration;
  }


  public void setConfiguration(Map<String, Object> _configuration) {
    
    
    
    this._configuration = _configuration;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ConnectorsCreateNewConnectorRequestConnector instance itself
   */
  public ConnectorsCreateNewConnectorRequestConnector putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorsCreateNewConnectorRequestConnector connectorsCreateNewConnectorRequestConnector = (ConnectorsCreateNewConnectorRequestConnector) o;
    return Objects.equals(this.name, connectorsCreateNewConnectorRequestConnector.name) &&
        Objects.equals(this.connectorType, connectorsCreateNewConnectorRequestConnector.connectorType) &&
        Objects.equals(this.connectorName, connectorsCreateNewConnectorRequestConnector.connectorName) &&
        Objects.equals(this._configuration, connectorsCreateNewConnectorRequestConnector._configuration)&&
        Objects.equals(this.additionalProperties, connectorsCreateNewConnectorRequestConnector.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, connectorType, connectorName, _configuration, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorsCreateNewConnectorRequestConnector {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    connectorType: ").append(toIndentedString(connectorType)).append("\n");
    sb.append("    connectorName: ").append(toIndentedString(connectorName)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("connector_type");
    openapiFields.add("connector_name");
    openapiFields.add("configuration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("connector_type");
    openapiRequiredFields.add("connector_name");
    openapiRequiredFields.add("configuration");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConnectorsCreateNewConnectorRequestConnector
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ConnectorsCreateNewConnectorRequestConnector.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConnectorsCreateNewConnectorRequestConnector is not found in the empty JSON string", ConnectorsCreateNewConnectorRequestConnector.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConnectorsCreateNewConnectorRequestConnector.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("connector_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connector_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connector_type").toString()));
      }
      if (!jsonObj.get("connector_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connector_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connector_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectorsCreateNewConnectorRequestConnector.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectorsCreateNewConnectorRequestConnector' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectorsCreateNewConnectorRequestConnector> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectorsCreateNewConnectorRequestConnector.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectorsCreateNewConnectorRequestConnector>() {
           @Override
           public void write(JsonWriter out, ConnectorsCreateNewConnectorRequestConnector value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectorsCreateNewConnectorRequestConnector read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ConnectorsCreateNewConnectorRequestConnector instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConnectorsCreateNewConnectorRequestConnector given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConnectorsCreateNewConnectorRequestConnector
  * @throws IOException if the JSON string is invalid with respect to ConnectorsCreateNewConnectorRequestConnector
  */
  public static ConnectorsCreateNewConnectorRequestConnector fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectorsCreateNewConnectorRequestConnector.class);
  }

 /**
  * Convert an instance of ConnectorsCreateNewConnectorRequestConnector to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

