/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner;
import com.konfigthis.client.model.ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReportsGetDataBasedOnTypeResponseData
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReportsGetDataBasedOnTypeResponseData {
  public static final String SERIALIZED_NAME_SYNC_RUN_TRIGGERED = "sync_run_triggered";
  @SerializedName(SERIALIZED_NAME_SYNC_RUN_TRIGGERED)
  private List<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner> syncRunTriggered = null;

  public static final String SERIALIZED_NAME_TOTAL_SYNC_RUN_ROWS = "total_sync_run_rows";
  @SerializedName(SERIALIZED_NAME_TOTAL_SYNC_RUN_ROWS)
  private List<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner> totalSyncRunRows = null;

  public ReportsGetDataBasedOnTypeResponseData() {
  }

  public ReportsGetDataBasedOnTypeResponseData syncRunTriggered(List<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner> syncRunTriggered) {
    
    
    
    
    this.syncRunTriggered = syncRunTriggered;
    return this;
  }

  public ReportsGetDataBasedOnTypeResponseData addSyncRunTriggeredItem(ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner syncRunTriggeredItem) {
    if (this.syncRunTriggered == null) {
      this.syncRunTriggered = new ArrayList<>();
    }
    this.syncRunTriggered.add(syncRunTriggeredItem);
    return this;
  }

   /**
   * Get syncRunTriggered
   * @return syncRunTriggered
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner> getSyncRunTriggered() {
    return syncRunTriggered;
  }


  public void setSyncRunTriggered(List<ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner> syncRunTriggered) {
    
    
    
    this.syncRunTriggered = syncRunTriggered;
  }


  public ReportsGetDataBasedOnTypeResponseData totalSyncRunRows(List<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner> totalSyncRunRows) {
    
    
    
    
    this.totalSyncRunRows = totalSyncRunRows;
    return this;
  }

  public ReportsGetDataBasedOnTypeResponseData addTotalSyncRunRowsItem(ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner totalSyncRunRowsItem) {
    if (this.totalSyncRunRows == null) {
      this.totalSyncRunRows = new ArrayList<>();
    }
    this.totalSyncRunRows.add(totalSyncRunRowsItem);
    return this;
  }

   /**
   * Get totalSyncRunRows
   * @return totalSyncRunRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner> getTotalSyncRunRows() {
    return totalSyncRunRows;
  }


  public void setTotalSyncRunRows(List<ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner> totalSyncRunRows) {
    
    
    
    this.totalSyncRunRows = totalSyncRunRows;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReportsGetDataBasedOnTypeResponseData instance itself
   */
  public ReportsGetDataBasedOnTypeResponseData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportsGetDataBasedOnTypeResponseData reportsGetDataBasedOnTypeResponseData = (ReportsGetDataBasedOnTypeResponseData) o;
    return Objects.equals(this.syncRunTriggered, reportsGetDataBasedOnTypeResponseData.syncRunTriggered) &&
        Objects.equals(this.totalSyncRunRows, reportsGetDataBasedOnTypeResponseData.totalSyncRunRows)&&
        Objects.equals(this.additionalProperties, reportsGetDataBasedOnTypeResponseData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncRunTriggered, totalSyncRunRows, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportsGetDataBasedOnTypeResponseData {\n");
    sb.append("    syncRunTriggered: ").append(toIndentedString(syncRunTriggered)).append("\n");
    sb.append("    totalSyncRunRows: ").append(toIndentedString(totalSyncRunRows)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sync_run_triggered");
    openapiFields.add("total_sync_run_rows");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReportsGetDataBasedOnTypeResponseData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReportsGetDataBasedOnTypeResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReportsGetDataBasedOnTypeResponseData is not found in the empty JSON string", ReportsGetDataBasedOnTypeResponseData.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("sync_run_triggered") != null && !jsonObj.get("sync_run_triggered").isJsonNull()) {
        JsonArray jsonArraysyncRunTriggered = jsonObj.getAsJsonArray("sync_run_triggered");
        if (jsonArraysyncRunTriggered != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sync_run_triggered").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sync_run_triggered` to be an array in the JSON string but got `%s`", jsonObj.get("sync_run_triggered").toString()));
          }

          // validate the optional field `sync_run_triggered` (array)
          for (int i = 0; i < jsonArraysyncRunTriggered.size(); i++) {
            ReportsGetDataBasedOnTypeResponseDataSyncRunTriggeredInner.validateJsonObject(jsonArraysyncRunTriggered.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("total_sync_run_rows") != null && !jsonObj.get("total_sync_run_rows").isJsonNull()) {
        JsonArray jsonArraytotalSyncRunRows = jsonObj.getAsJsonArray("total_sync_run_rows");
        if (jsonArraytotalSyncRunRows != null) {
          // ensure the json data is an array
          if (!jsonObj.get("total_sync_run_rows").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `total_sync_run_rows` to be an array in the JSON string but got `%s`", jsonObj.get("total_sync_run_rows").toString()));
          }

          // validate the optional field `total_sync_run_rows` (array)
          for (int i = 0; i < jsonArraytotalSyncRunRows.size(); i++) {
            ReportsGetDataBasedOnTypeResponseDataTotalSyncRunRowsInner.validateJsonObject(jsonArraytotalSyncRunRows.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReportsGetDataBasedOnTypeResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReportsGetDataBasedOnTypeResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReportsGetDataBasedOnTypeResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReportsGetDataBasedOnTypeResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<ReportsGetDataBasedOnTypeResponseData>() {
           @Override
           public void write(JsonWriter out, ReportsGetDataBasedOnTypeResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReportsGetDataBasedOnTypeResponseData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReportsGetDataBasedOnTypeResponseData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReportsGetDataBasedOnTypeResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReportsGetDataBasedOnTypeResponseData
  * @throws IOException if the JSON string is invalid with respect to ReportsGetDataBasedOnTypeResponseData
  */
  public static ReportsGetDataBasedOnTypeResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReportsGetDataBasedOnTypeResponseData.class);
  }

 /**
  * Convert an instance of ReportsGetDataBasedOnTypeResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

