/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SyncRunsListBySyncIdResponseDataInnerAttributes
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SyncRunsListBySyncIdResponseDataInnerAttributes {
  public static final String SERIALIZED_NAME_SYNC_ID = "sync_id";
  @SerializedName(SERIALIZED_NAME_SYNC_ID)
  private Integer syncId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STARTED_AT = "started_at";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private OffsetDateTime startedAt;

  public static final String SERIALIZED_NAME_FINISHED_AT = "finished_at";
  @SerializedName(SERIALIZED_NAME_FINISHED_AT)
  private OffsetDateTime finishedAt;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private Float duration;

  public static final String SERIALIZED_NAME_TOTAL_QUERY_ROWS = "total_query_rows";
  @SerializedName(SERIALIZED_NAME_TOTAL_QUERY_ROWS)
  private Integer totalQueryRows;

  public static final String SERIALIZED_NAME_TOTAL_ROWS = "total_rows";
  @SerializedName(SERIALIZED_NAME_TOTAL_ROWS)
  private Integer totalRows;

  public static final String SERIALIZED_NAME_SUCCESSFUL_ROWS = "successful_rows";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL_ROWS)
  private Integer successfulRows;

  public static final String SERIALIZED_NAME_FAILED_ROWS = "failed_rows";
  @SerializedName(SERIALIZED_NAME_FAILED_ROWS)
  private Integer failedRows;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public SyncRunsListBySyncIdResponseDataInnerAttributes() {
  }

  public SyncRunsListBySyncIdResponseDataInnerAttributes syncId(Integer syncId) {
    
    
    
    
    this.syncId = syncId;
    return this;
  }

   /**
   * Get syncId
   * @return syncId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSyncId() {
    return syncId;
  }


  public void setSyncId(Integer syncId) {
    
    
    
    this.syncId = syncId;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes startedAt(OffsetDateTime startedAt) {
    
    
    
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartedAt() {
    return startedAt;
  }


  public void setStartedAt(OffsetDateTime startedAt) {
    
    
    
    this.startedAt = startedAt;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes finishedAt(OffsetDateTime finishedAt) {
    
    
    
    
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * Get finishedAt
   * @return finishedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getFinishedAt() {
    return finishedAt;
  }


  public void setFinishedAt(OffsetDateTime finishedAt) {
    
    
    
    this.finishedAt = finishedAt;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes duration(Float duration) {
    
    
    
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getDuration() {
    return duration;
  }


  public void setDuration(Float duration) {
    
    
    
    this.duration = duration;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes totalQueryRows(Integer totalQueryRows) {
    
    
    
    
    this.totalQueryRows = totalQueryRows;
    return this;
  }

   /**
   * Get totalQueryRows
   * @return totalQueryRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalQueryRows() {
    return totalQueryRows;
  }


  public void setTotalQueryRows(Integer totalQueryRows) {
    
    
    
    this.totalQueryRows = totalQueryRows;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes totalRows(Integer totalRows) {
    
    
    
    
    this.totalRows = totalRows;
    return this;
  }

   /**
   * Get totalRows
   * @return totalRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalRows() {
    return totalRows;
  }


  public void setTotalRows(Integer totalRows) {
    
    
    
    this.totalRows = totalRows;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes successfulRows(Integer successfulRows) {
    
    
    
    
    this.successfulRows = successfulRows;
    return this;
  }

   /**
   * Get successfulRows
   * @return successfulRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSuccessfulRows() {
    return successfulRows;
  }


  public void setSuccessfulRows(Integer successfulRows) {
    
    
    
    this.successfulRows = successfulRows;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes failedRows(Integer failedRows) {
    
    
    
    
    this.failedRows = failedRows;
    return this;
  }

   /**
   * Get failedRows
   * @return failedRows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getFailedRows() {
    return failedRows;
  }


  public void setFailedRows(Integer failedRows) {
    
    
    
    this.failedRows = failedRows;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes error(String error) {
    
    
    
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    
    
    
    this.error = error;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes createdAt(OffsetDateTime createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public SyncRunsListBySyncIdResponseDataInnerAttributes updatedAt(OffsetDateTime updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SyncRunsListBySyncIdResponseDataInnerAttributes instance itself
   */
  public SyncRunsListBySyncIdResponseDataInnerAttributes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncRunsListBySyncIdResponseDataInnerAttributes syncRunsListBySyncIdResponseDataInnerAttributes = (SyncRunsListBySyncIdResponseDataInnerAttributes) o;
    return Objects.equals(this.syncId, syncRunsListBySyncIdResponseDataInnerAttributes.syncId) &&
        Objects.equals(this.status, syncRunsListBySyncIdResponseDataInnerAttributes.status) &&
        Objects.equals(this.startedAt, syncRunsListBySyncIdResponseDataInnerAttributes.startedAt) &&
        Objects.equals(this.finishedAt, syncRunsListBySyncIdResponseDataInnerAttributes.finishedAt) &&
        Objects.equals(this.duration, syncRunsListBySyncIdResponseDataInnerAttributes.duration) &&
        Objects.equals(this.totalQueryRows, syncRunsListBySyncIdResponseDataInnerAttributes.totalQueryRows) &&
        Objects.equals(this.totalRows, syncRunsListBySyncIdResponseDataInnerAttributes.totalRows) &&
        Objects.equals(this.successfulRows, syncRunsListBySyncIdResponseDataInnerAttributes.successfulRows) &&
        Objects.equals(this.failedRows, syncRunsListBySyncIdResponseDataInnerAttributes.failedRows) &&
        Objects.equals(this.error, syncRunsListBySyncIdResponseDataInnerAttributes.error) &&
        Objects.equals(this.createdAt, syncRunsListBySyncIdResponseDataInnerAttributes.createdAt) &&
        Objects.equals(this.updatedAt, syncRunsListBySyncIdResponseDataInnerAttributes.updatedAt)&&
        Objects.equals(this.additionalProperties, syncRunsListBySyncIdResponseDataInnerAttributes.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncId, status, startedAt, finishedAt, duration, totalQueryRows, totalRows, successfulRows, failedRows, error, createdAt, updatedAt, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncRunsListBySyncIdResponseDataInnerAttributes {\n");
    sb.append("    syncId: ").append(toIndentedString(syncId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    totalQueryRows: ").append(toIndentedString(totalQueryRows)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("    successfulRows: ").append(toIndentedString(successfulRows)).append("\n");
    sb.append("    failedRows: ").append(toIndentedString(failedRows)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sync_id");
    openapiFields.add("status");
    openapiFields.add("started_at");
    openapiFields.add("finished_at");
    openapiFields.add("duration");
    openapiFields.add("total_query_rows");
    openapiFields.add("total_rows");
    openapiFields.add("successful_rows");
    openapiFields.add("failed_rows");
    openapiFields.add("error");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SyncRunsListBySyncIdResponseDataInnerAttributes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SyncRunsListBySyncIdResponseDataInnerAttributes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SyncRunsListBySyncIdResponseDataInnerAttributes is not found in the empty JSON string", SyncRunsListBySyncIdResponseDataInnerAttributes.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("error").isJsonNull() && (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SyncRunsListBySyncIdResponseDataInnerAttributes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SyncRunsListBySyncIdResponseDataInnerAttributes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SyncRunsListBySyncIdResponseDataInnerAttributes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SyncRunsListBySyncIdResponseDataInnerAttributes.class));

       return (TypeAdapter<T>) new TypeAdapter<SyncRunsListBySyncIdResponseDataInnerAttributes>() {
           @Override
           public void write(JsonWriter out, SyncRunsListBySyncIdResponseDataInnerAttributes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SyncRunsListBySyncIdResponseDataInnerAttributes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SyncRunsListBySyncIdResponseDataInnerAttributes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SyncRunsListBySyncIdResponseDataInnerAttributes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SyncRunsListBySyncIdResponseDataInnerAttributes
  * @throws IOException if the JSON string is invalid with respect to SyncRunsListBySyncIdResponseDataInnerAttributes
  */
  public static SyncRunsListBySyncIdResponseDataInnerAttributes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SyncRunsListBySyncIdResponseDataInnerAttributes.class);
  }

 /**
  * Convert an instance of SyncRunsListBySyncIdResponseDataInnerAttributes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

