/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.SyncRunsListBySyncIdResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SyncRunsApi
 */
@Disabled
public class SyncRunsApiTest {

    private static SyncRunsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SyncRunsApi(apiClient);
    }

    /**
     * List sync runs for a specific sync
     *
     * Retrieves a list of sync runs for a specific sync, optionally filtered by status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBySyncIdTest() throws ApiException {
        Integer syncId = null;
        String status = null;
        Integer page = null;
        SyncRunsListBySyncIdResponse response = api.listBySyncId(syncId)
                .status(status)
                .page(page)
                .execute();
        // TODO: test validations
    }

}
