/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.SyncRecordsListForSyncRunResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SyncRecordsApi
 */
@Disabled
public class SyncRecordsApiTest {

    private static SyncRecordsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SyncRecordsApi(apiClient);
    }

    /**
     * List sync records for a specific sync run
     *
     * Retrieves a list of sync records for a specific sync run, optionally filtered by status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listForSyncRunTest() throws ApiException {
        Integer syncId = null;
        Integer syncRunId = null;
        String status = null;
        Integer page = null;
        SyncRecordsListForSyncRunResponse response = api.listForSyncRun(syncId, syncRunId)
                .status(status)
                .page(page)
                .execute();
        // TODO: test validations
    }

}
