/*
 * MultiWoven API
 * Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.SyncRecordsListForSyncRunResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class SyncRecordsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SyncRecordsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public SyncRecordsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call listForSyncRunCall(Integer syncId, Integer syncRunId, String status, Integer page, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/syncs/{sync_id}/sync_runs/{sync_run_id}/sync_records"
            .replace("{" + "sync_id" + "}", localVarApiClient.escapeString(syncId.toString()))
            .replace("{" + "sync_run_id" + "}", localVarApiClient.escapeString(syncRunId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listForSyncRunValidateBeforeCall(Integer syncId, Integer syncRunId, String status, Integer page, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'syncId' is set
        if (syncId == null) {
            throw new ApiException("Missing the required parameter 'syncId' when calling listForSyncRun(Async)");
        }

        // verify the required parameter 'syncRunId' is set
        if (syncRunId == null) {
            throw new ApiException("Missing the required parameter 'syncRunId' when calling listForSyncRun(Async)");
        }

        return listForSyncRunCall(syncId, syncRunId, status, page, _callback);

    }


    private ApiResponse<SyncRecordsListForSyncRunResponse> listForSyncRunWithHttpInfo(Integer syncId, Integer syncRunId, String status, Integer page) throws ApiException {
        okhttp3.Call localVarCall = listForSyncRunValidateBeforeCall(syncId, syncRunId, status, page, null);
        Type localVarReturnType = new TypeToken<SyncRecordsListForSyncRunResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listForSyncRunAsync(Integer syncId, Integer syncRunId, String status, Integer page, final ApiCallback<SyncRecordsListForSyncRunResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listForSyncRunValidateBeforeCall(syncId, syncRunId, status, page, _callback);
        Type localVarReturnType = new TypeToken<SyncRecordsListForSyncRunResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListForSyncRunRequestBuilder {
        private final Integer syncId;
        private final Integer syncRunId;
        private String status;
        private Integer page;

        private ListForSyncRunRequestBuilder(Integer syncId, Integer syncRunId) {
            this.syncId = syncId;
            this.syncRunId = syncRunId;
        }

        /**
         * Set status
         * @param status Optional status to filter the sync records by. (optional)
         * @return ListForSyncRunRequestBuilder
         */
        public ListForSyncRunRequestBuilder status(String status) {
            this.status = status;
            return this;
        }
        
        /**
         * Set page
         * @param page Page number for pagination. (optional)
         * @return ListForSyncRunRequestBuilder
         */
        public ListForSyncRunRequestBuilder page(Integer page) {
            this.page = page;
            return this;
        }
        
        /**
         * Build call for listForSyncRun
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A JSON array of sync records </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listForSyncRunCall(syncId, syncRunId, status, page, _callback);
        }


        /**
         * Execute listForSyncRun request
         * @return SyncRecordsListForSyncRunResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A JSON array of sync records </td><td>  -  </td></tr>
         </table>
         */
        public SyncRecordsListForSyncRunResponse execute() throws ApiException {
            ApiResponse<SyncRecordsListForSyncRunResponse> localVarResp = listForSyncRunWithHttpInfo(syncId, syncRunId, status, page);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute listForSyncRun request with HTTP info returned
         * @return ApiResponse&lt;SyncRecordsListForSyncRunResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A JSON array of sync records </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<SyncRecordsListForSyncRunResponse> executeWithHttpInfo() throws ApiException {
            return listForSyncRunWithHttpInfo(syncId, syncRunId, status, page);
        }

        /**
         * Execute listForSyncRun request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> A JSON array of sync records </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<SyncRecordsListForSyncRunResponse> _callback) throws ApiException {
            return listForSyncRunAsync(syncId, syncRunId, status, page, _callback);
        }
    }

    /**
     * List sync records for a specific sync run
     * Retrieves a list of sync records for a specific sync run, optionally filtered by status.
     * @param syncId The ID of the sync to list records for. (required)
     * @param syncRunId The ID of the sync run to list records for. (required)
     * @return ListForSyncRunRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A JSON array of sync records </td><td>  -  </td></tr>
     </table>
     */
    public ListForSyncRunRequestBuilder listForSyncRun(Integer syncId, Integer syncRunId) throws IllegalArgumentException {
        if (syncId == null) throw new IllegalArgumentException("\"syncId\" is required but got null");
        if (syncRunId == null) throw new IllegalArgumentException("\"syncRunId\" is required but got null");
        return new ListForSyncRunRequestBuilder(syncId, syncRunId);
    }
}
